// Gamification badges — computed on the fly from /user/stats, no separate
// badge/streak schema. Adding a new badge is a one-line addition here.

import { ImageSourcePropType } from "react-native";
import { UserStats } from "./api";

// label/requirement text lives in i18n (badges.<id>.label / .requirement in
// src/i18n/locales/*.json), not here — this file only knows ids, icons, and
// earn logic, so callers must translate via t(`badges.${id}.label`).
export interface Badge {
  id: string;
  emoji: string;
  // Real wood-carved artwork -- see mobile/assets/badges/. Falls back to
  // the emoji if a badge doesn't have one yet.
  icon?: ImageSourcePropType;
  // True-grayscale render of the same artwork (see assets/badges/grey/),
  // generated by converting RGB to luminance while keeping the original
  // alpha mask -- used anywhere an unearned badge needs to read as
  // literally colorless rather than just a dimmed/faded color icon.
  greyIcon?: ImageSourcePropType;
}

export interface BadgeStatus extends Badge {
  earned: boolean;
}

// Ordered easiest to hardest (a difficulty proxy, not a stored field --
// there's no single unit shared across streak days/km/cities/likes, so
// this is a judgment call baked into array order rather than a computed
// sort). getAllBadges()/getEarnedBadges() both just map over this in
// order, so reordering here is the whole "easiest first" feature.
const BADGE_DEFS: { id: string; emoji: string; icon?: ImageSourcePropType; greyIcon?: ImageSourcePropType; earned: (s: UserStats) => boolean }[] = [
  { id: "first_steps", emoji: "👣", icon: require("../../assets/badges/first_steps.png"), greyIcon: require("../../assets/badges/grey/first_steps.png"), earned: (s) => s.tours_completed >= 1 },
  { id: "on_a_roll", emoji: "🔥", icon: require("../../assets/badges/on_a_roll.png"), greyIcon: require("../../assets/badges/grey/on_a_roll.png"), earned: (s) => s.longest_streak_days >= 3 },
  { id: "early_bird", emoji: "🌅", icon: require("../../assets/badges/early_bird.png"), greyIcon: require("../../assets/badges/grey/early_bird.png"), earned: (s) => s.early_streak_days >= 7 },
  { id: "night_owl", emoji: "🌙", icon: require("../../assets/badges/night_owl.png"), greyIcon: require("../../assets/badges/grey/night_owl.png"), earned: (s) => s.night_streak_days >= 7 },
  { id: "week_streak", emoji: "🔥🔥", icon: require("../../assets/badges/week_streak.png"), greyIcon: require("../../assets/badges/grey/week_streak.png"), earned: (s) => s.longest_streak_days >= 7 },
  { id: "marathoner", emoji: "🏅", icon: require("../../assets/badges/marathoner.png"), greyIcon: require("../../assets/badges/grey/marathoner.png"), earned: (s) => s.total_distance_m >= 75_000 },
  { id: "explorer", emoji: "🧭", icon: require("../../assets/badges/explorer.png"), greyIcon: require("../../assets/badges/grey/explorer.png"), earned: (s) => s.cities_visited >= 5 },
  { id: "completionist", emoji: "🌟", icon: require("../../assets/badges/completionist.png"), greyIcon: require("../../assets/badges/grey/completionist.png"), earned: (s) => s.moods_tried.length >= 5 },
  { id: "iron_streak", emoji: "🏆", icon: require("../../assets/badges/iron_streak.png"), greyIcon: require("../../assets/badges/grey/iron_streak.png"), earned: (s) => s.longest_streak_days >= 30 },
  { id: "storyteller", emoji: "📖", icon: require("../../assets/badges/storyteller.png"), greyIcon: require("../../assets/badges/grey/storyteller.png"), earned: (s) => s.routes_published >= 8 },
  { id: "crowd_favorite", emoji: "❤️", icon: require("../../assets/badges/crowd_favorite.png"), greyIcon: require("../../assets/badges/grey/crowd_favorite.png"), earned: (s) => s.total_likes_received >= 30 },
  { id: "century_club", emoji: "💯", icon: require("../../assets/badges/century_club.png"), greyIcon: require("../../assets/badges/grey/century_club.png"), earned: (s) => s.total_distance_m >= 200_000 },
  { id: "world_traveler", emoji: "🌍", icon: require("../../assets/badges/world_traveler.png"), greyIcon: require("../../assets/badges/grey/world_traveler.png"), earned: (s) => s.cities_visited >= 10 },
];

export function getEarnedBadges(stats: UserStats): Badge[] {
  return BADGE_DEFS.filter((b) => b.earned(stats)).map(({ id, emoji, icon }) => ({ id, emoji, icon }));
}

// Every badge, earned or not — powers the badge gallery screen (locked
// ones shown greyed out with what's needed to unlock them).
export function getAllBadges(stats: UserStats): BadgeStatus[] {
  return BADGE_DEFS.map(({ id, emoji, icon, greyIcon, earned }) => ({
    id,
    emoji,
    icon,
    greyIcon,
    earned: earned(stats),
  }));
}
